version: '3'

services:

  ss2023_wa_derfruehundderspaetaufsteher_recipe:
    container_name: ss2023_wa_derfruehundderspaetaufsteher_recipe
    ports:
      - "20073:20073"
    networks:
      - ss2023_wa_derfruehundderspaetaufsteher
    build: ./backend/recipes
    depends_on:
      - ss2023_wa_derfruehundderspaetaufsteher_database

  ss2023_wa_derfruehundderspaetaufsteher_calories:
    container_name: ss2023_wa_derfruehundderspaetaufsteher_calories
    ports:
      - "20074:20074"
    networks:
      - ss2023_wa_derfruehundderspaetaufsteher
    build: ./backend/calories
    depends_on:
      - ss2023_wa_derfruehundderspaetaufsteher_database

  ss2023_wa_derfruehundderspaetaufsteher_ingredients:
    container_name: ss2023_wa_derfruehundderspaetaufsteher_ingredients
    ports:
      - "20075:20075"
    networks:
      - ss2023_wa_derfruehundderspaetaufsteher
    build: ./backend/ingredients
    depends_on:
      - ss2023_wa_derfruehundderspaetaufsteher_database

  # mongodb
  ss2023_wa_derfruehundderspaetaufsteher_database:
    container_name: ss2023_wa_derfruehundderspaetaufsteher_database
    image: mongo:4.4
    restart: always
    ports:
      - "20072:27017"
    networks:
      - ss2023_wa_derfruehundderspaetaufsteher
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    depends_on:
      - ss2023_wa_derfruehundderspaetaufsteher_database
    restart: always
    ports:
      - "20076:8081"
    networks:
      - ss2023_wa_derfruehundderspaetaufsteher
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@ss2023_wa_derfruehundderspaetaufsteher_database:27017/

networks:
  ss2023_wa_derfruehundderspaetaufsteher: